zero:
	python3 generate.py data/structure0.txt data/words0.txt result0.png

one:
	python3 generate.py data/structure1.txt data/words1.txt result1.png

two:
	python3 generate.py data/structure2.txt data/words2.txt result2.png
